COLOR_TOPIC = "/camera/camera/color/image_raw"
DEPTH_TOPIC = "/camera/camera/aligned_depth_to_color/image_raw"

MAP_TOPIC = "/map"
POSE_TOPIC = "/pose"
MAP_FRAME = "map"
BASE_FRAME = "base_link"

ROI_HEIGHT_RATIO = 0.6
SECTION_COUNT = 5

VALID_MIN_M = 0.2
VALID_MAX_M = 1.2
AVOID_DISTANCE_M = 0.4

NEAR_RATIO_THRESHOLD = 0.08
MIN_BLOB_AREA = 500
STABLE_FRAME_COUNT = 3

DASHBOARD_WINDOW_NAME = "ss_depth dashboard"
DASHBOARD_TIMER_SEC = 0.03
WAIT_KEY_DELAY_MS = 1

MAP_VIEW_WIDTH = 800
MAP_VIEW_HEIGHT = 600
CAMERA_VIEW_WIDTH = 800
CAMERA_VIEW_HEIGHT = 600

DEFAULT_GOAL_X_M = 2.0
DEFAULT_GOAL_Y_M = 0.0
